#############################################################################
# config for loading maze simulation #
#############################################################################
### GLOBAL PARAMS
output_dir: "logs/" # 'output/trial0'

plot:
  y_axis_limit: 18  # limits the y-axis of the plot
  show: false       # true will show planner plots

demo_mode: false     # when using demo mode, control both forward and angular speed

# obstacles information
randomize_obstacles: true
num_obstacles: 5
obstacle_size: 0.5
min_obs_dist: 0.62       # minimum obstacle distance during random initialization
max_obs_x: 15
min_obs_x: 0
max_obs_y: 15
min_obs_y: 0

# parameters for low-dim environment
low_dim_state: false
fixed_trial_idx: 1
random_start: false
start_x_range: 20
start_y_range: 20

### PLANNER PARAMS
#max_replan: 1        # max number of replans
concentration: 0.1    # options are 0.2, 0.3, 0.4, 0.5
planner: 'predictive'    # options are 'skeleton', 'straight', or 'lattice'
goal_x: 3.75
goal_y: 3.75
goal_radius: 1
threshold_dist: 0.5   # fraction of path length for deciding whether to update planned path
threshold_cost: 0.95  # fraction of path cost for deciding whether to update planned path
occ:     # occupancy map grid size
  m_to_pix_scale: 16   # number of pixels per meter when generating the raw occupancy map
  map_height: 15       # occupancy map height (in meter)
  map_width: 15       # occupancy map width (in meter)
  local_width: 12      # local moving window width (in meter)
  local_height: 12     # local moving window height (in meter)
a_star:
  horizon: 30  # receding horizon in metres (needs to be an int for it to be enabled)
  replan: true
  smooth_path:
    add_nodes: 10  # number of nodes to add in node path
    max_dist: 20   # max distance to consider a pair of nodes
  weight: 1        # static weighting for weighed A* f(n) = g(n) + w * h(n) where weight > 1
#  h_baseline: True  # if true, then heuristic is simply euclidean distance to goal
costmap:
  m: 40       # height of ice channel in metres, can set to large number for 'infinite' ice channel
  n: 16       # width of ice channel in metres
  scale: 5    # this gives a resolution of 1/scale x 1/scale metres
  alpha: 10   # collision cost multiplier
prim:
  scale: 5 # Note, there is a limit on how small prim scale can be in relation to costmap scale
  num_headings: 8  # number of headings in the discretized heading space
  step_size: 0.1   # step size for sampling points on the path
  turning_radius: 2.0  # turning radius of the ship in lattice units
robot:
  mass: 1  # mass of the NRC ship in kg
  padding: 0.25  # adds padding to ship footprint
  min_r: 0.6      # the smaller size of the robot

  vertices: [
              # [0.51, -0.9],
              # [-0.51, -0.67],

              # [-0.51, 0.67],
              # [0.51, 0.9], 

              [0.7, -0.5],
              [0.55, -0.6],
              [-0.55, -0.6],
              [-0.7, -0.5],

              [-0.7, 0.5],
              [-0.55, 0.6],
              [0.55, 0.6], 
              [0.7, 0.5]
              ]
  
  wheel_vertices: [
    # left front
    [
        [0.2, 0.6],
        [0.2, 0.7],
        [0.5, 0.7], 
        [0.55, 0.6]
    ],

    # right front
    [
        [0.2, -0.7],
        [0.2, -0.6],
        [0.55, -0.6], 
        [0.55, -0.7]
    ],

    # left rear
    [
        [-0.2, 0.6],
        [-0.2, 0.7],
        [-0.55, 0.7], 
        [-0.55, 0.6]
    ],

    # right rear
    [
        [-0.2, -0.6],
        [-0.2, -0.7],
        [-0.55, -0.7], 
        [-0.55, -0.6]
    ],
  ]
  min_obstacle_dist: 2.5  # minimum distance to between robot location and walls
### SIMULATION PARAMS
render:
  log_obs: false       # whether to log occupancy observation
  show: true          # if true show simulation plots
sim:
  t_max: 2000  # max number of iterations in simulation loop (originally 5000)
  steps: 400    # number of simulation steps per iteration (originally 10)
  gravity: !!python/tuple
    - 0
    - 0
  iterations: 10  # controls accuracy of pymunk solver i.e. simulation accuracy, default is 10
  damping: 0      # damping to body velocities
  obstacle_density: 0.001
anim:
  save: true               # if true save to disk animation plots
  show: true                # if true show animation plots
  plot_steps: 50            # steps between plot updates
  plan_steps: 10            # steps between obstacle and planner updates
  inf_stream: false         # if true then infinite obstacle stream mode is enabled
  move_yaxis_threshold: 10  # distance traveled before y-axis moves
#  new_obs_dist: 50          # distance traveled before new obstacles are added
seed: 1
#ice_current: [0, -1]       # option to add ice current to simulation

### SHIP MODEL AND CONTROLLER PARAMS
controller:
  dt: 0.8  # the ship dynamics model was discretized with this dt (originally 0.02)
  # States: [r, u, v] : yaw rate (deg/s), surge velocity (m/s), sway velocity (m/s)
  A:
    - [ 0.9909, 0., 0. ]
    - [ 0., 0.9980, 0. ]
    - [ 0., 0., 0.9953 ]
  # Input matrix: differential fore/aft (rps), side tunnel (rps), main prop (rps) (Assume pure motions)
  B: [ 0.04515, 4.321e-5, 1.730e-4 ]
  # Input limits
  # To calculate yaw rate given min turn radius r and surge velocity v
  # 360 / ((2 pi r) / v)
  input_lims: [8.6, 0.5, 0.05]
  # look ahead distance
  Lfc: 0.5
  # target speed
  target_speed: 10  # m/s
  PID_gains:  # gains for 3 PIDs
    - [ 5, 0, 5 ]
    - [ 10, 0, 20 ]
    - [ 10, 0, 20 ]

#env parameters
env:
  length: 15
  width: 15
  #maze versions 1 and 2 are available
  maze_version: 1

train:
  train_mode: false
  job_type: ppo # options are ppo, sac
  job_name: 'maze_ppo'
  total_timesteps: 15e5
  checkpoint_freq: 10000

evaluate:
  eval_mode: true
  num_eps: 1
  policy_types: []  # list of policy types to evaluate
  action_types: []  # list of action types to evaluate
  models: []        # list of model names to evaluate
  