#############################################################################
# config for loading ship-ice simulation #
#############################################################################
### GLOBAL PARAMS
output_dir: "logs/" # 'output/trial0'

plot:
  y_axis_limit: 18  # limits the y-axis of the plot
  show: false       # true will show planner plots

demo_mode: false     # when using demo mode, control both forward and angular speed

# cubes information
randomize_cubes: true
num_cubes: 10
cube_size: 0.44
min_cube_dist: 0.62       # minimum cube distance during random initialization
max_cube_x: 4
min_cube_x: -4
max_cube_y: 2
min_cube_y: -2

# parameters for low-dim environment
low_dim_state: false
fixed_trial_idx: 1
random_start: true
start_x_range: 15

### PLANNER PARAMS
#max_replan: 1        # max number of replans
concentration: 0.1    # options are 0.2, 0.3, 0.4, 0.5
planner: 'predictive'    # options are 'skeleton', 'straight', or 'lattice'
goal_y: 15
threshold_dist: 0.5   # fraction of path length for deciding whether to update planned path
threshold_cost: 0.95  # fraction of path cost for deciding whether to update planned path
occ:
  grid_size: 0.2       # occupancy map grid size
  m_to_pix_scale: 19.5   # number of pixels per meter when generating the raw occupancy map
  map_height: 28       # occupancy map height (in meter)
  map_width: 16        # occupancy map width (in meter)
a_star:
  horizon: 30  # receding horizon in metres (needs to be an int for it to be enabled)
  replan: true
  smooth_path:
    add_nodes: 10  # number of nodes to add in node path
    max_dist: 20   # max distance to consider a pair of nodes
  weight: 1        # static weighting for weighed A* f(n) = g(n) + w * h(n) where weight > 1
#  h_baseline: True  # if true, then heuristic is simply euclidean distance to goal
costmap:
  m: 40       # height of ice channel in metres, can set to large number for 'infinite' ice channel
  n: 16       # width of ice channel in metres
  scale: 5    # this gives a resolution of 1/scale x 1/scale metres
  alpha: 10   # collision cost multiplier
prim:
  scale: 5 # Note, there is a limit on how small prim scale can be in relation to costmap scale
  num_headings: 8  # number of headings in the discretized heading space
  step_size: 0.1   # step size for sampling points on the path
  turning_radius: 2.0  # turning radius of the ship in lattice units
agent:
  mass: 1  # mass of the NRC ship in kg
  padding: 0.25  # adds padding to ship footprint
  length: 0.8
  width: 0.7
  vertices: [

              # [0.69, -0.89],
              # [-0.69, -0.89],

              # [-0.69, 0.89],
              # [0.69, 0.89], 

              # [0.69, -1.2],
              # [-0.69, -0.89],

              # [-0.69, 0.89],
              # [0.69, 1.2], 

              [0.4, -0.35],
              [0.4, 0.35],
              [-0.4, 0.25],
              [-0.4, -0.25]

              
              ]

### SIMULATION PARAMS
render:
  log_obs: false       # whether to log occupancy observation
  show: true          # if true show animation plots
  frequency: 20       # frequency of rendering
sim:
  t_max: 2000  # max number of iterations in simulation loop (originally 5000)
  steps: 100    # number of simulation steps per iteration (originally 10)
  gravity: !!python/tuple
    - 0
    - 0
  iterations: 10  # controls accuracy of pymunk solver i.e. simulation accuracy, default is 10
  damping: 0      # damping to body velocities
  cube_density: 0.001
anim:
  save: true               # if true save to disk animation plots
  show: true                # if true show animation plots
  plot_steps: 50            # steps between plot updates
  plan_steps: 10            # steps between obstacle and planner updates
  inf_stream: false         # if true then infinite obstacle stream mode is enabled
  move_yaxis_threshold: 10  # distance traveled before y-axis moves
#  new_obs_dist: 50          # distance traveled before new obstacles are added
seed: 1
#ice_current: [0, -1]       # option to add ice current to simulation

### SHIP MODEL AND CONTROLLER PARAMS
controller:
  dt: 0.2  # the ship dynamics model was discretized with this dt (originally 0.02)
  # States: [r, u, v] : yaw rate (deg/s), surge velocity (m/s), sway velocity (m/s)
  A:
    - [ 0.9909, 0., 0. ]
    - [ 0., 0.9980, 0. ]
    - [ 0., 0., 0.9953 ]
  # Input matrix: differential fore/aft (rps), side tunnel (rps), main prop (rps) (Assume pure motions)
  B: [ 0.04515, 4.321e-5, 1.730e-4 ]
  # Input limits
  # To calculate yaw rate given min turn radius r and surge velocity v
  # 360 / ((2 pi r) / v)
  input_lims: [8.6, 0.5, 0.05]
  # look ahead distance
  Lfc: 0.5
  # target speed
  target_speed: 0.3  # m/s
  PID_gains:  # gains for 3 PIDs
    - [ 5, 0, 5 ]
    - [ 10, 0, 20 ]
    - [ 10, 0, 20 ]

### ENVIRONMENT PARAMS
env:
  obstacle_config: small_columns # options are small_empty, small_columns, large_columns, large_divider
  room_length: 10
  room_width: 5 # 5 for small, 10 for large
  receptacle_width: 1.5
  shortest_path_channel_scale: 0.25
